### PR TITLE
Generate shipments change log

### PR DESCRIPTION
**Pull request by Levia**
This is about [Change-tracking of shipments in sandbox](https://www.pivotaltracker.com/story/show/132312937).
Although we already have papertrail in place for keeping track of the shipments' changes, we were missing the download of the changes themselves.
To achieve this, I've used [Phantom.js](http://phantomjs.org/), and in particular I reused and adapted one of the example they provide about doing [screenshots](http://phantomjs.org/screen-capture.html). So what happens is that phantom.js simulate the browser and goes to the required page, it renders that and does a screenshot converting it then to a pdf.
Since a log in to the `changes_history` page is required, I had to grant access to phantom.js by passing the cookie.
A requirement for this to work, is to [install phantom.js](http://phantomjs.org/download.html) in the server. Plus, since webrick is single thread, I can't test it here because it hangs on the phantom.js request, waiting for the other one to finish, but it should work fine on staging.

### CODE REVIEW

**Comment by Levia** [comment]
Included the ability to work with pagination and moved everything into an active job. The job will send an email with a zip file when finished.

**Comment by Levia** [comment]
Forgot to mention: you might need to add the `host` in your `.env` file

**Comment by agnessa** [comment]
I think this would still require some work to get it to a deployable state using the phantomjs technique - first and foremost there is a serious security issue with inputting the contents of a cookie onto the system command line, without any sanitisation or error checking whatsoever. In addition, the output doesn't look great - the table appears very narrow, with text hardly legible, and at least in the pdf readers I tried I had no ability to search by text or copy text from the document (sample of what got generated attached).

I think it might not be the best method to render such a potentially big amount of text data, especially if users might want to post-process it themselves; seems really good for rich graphics or maps, but what we need here is much simpler. Since we are short on time, I think we can't really go on with tweaking this. To finalise this task, I had a go at a simple CSV download that should tick all the boxes of the requirements and did not take too long to put in place as a workaround.
[changes_history_for_aru_916changes_history_1.pdf](https://github.com/unepwcmc/trade_reporting_tool/files/660996/changes_history_for_aru_916changes_history_1.pdf)

**Comment by Levia** [comment]
It might be a compatibility issue between Linux and Mac, but to me the pdf looks good and it's searchable as well. 
[changes_history_1.pdf](https://github.com/unepwcmc/trade_reporting_tool/files/661032/changes_history_1.pdf)

I thought that the problem with the CSV in this case is on how to clearly display which were the changes made.
But if you think a CSV is enough, I'm happy to go with that as well :)

**Pull request merged**
