### PR TITLE
Cache cleanup

### PR DESCRIPTION
**Pull request by Levia**
This is about [post submit cache cleanup](https://www.pivotaltracker.com/story/show/136418305).
It's reusing the same approach as SAPI and so I thought we are going to use the same folders structure.

### CODE REVIEW

**Comment by agnessa** [comment]
you mean we need to set up a shared directory for downloads? otherwise this cleans trt's downloads directory instead of sapi's.

**Comment by Levia** [comment]
I mean it's using the same logic but it's working on trt's folders. Was the original idea to have shared folders?

**Comment by agnessa** [comment]
No, the thing is we have no trade downloads in trt, so it is pointless to clear an empty directory :) Sorry, should have explained better. The way it works is that downloads from the public Trade interface (as well as admin) are cached in SAPI. Say somebody downloaded all trade in wolves from 2014 - that file gets cached, so that the next person who searches for same thing gets that file rather than re-run the whole business. Now in trt somebody uploads 100 shipments of wolf trade in 2014. Now's the time to destroy any cached files in SAPI, so that the next person who searches for wolves in 2014 gets the new data as well.

**Comment by Levia** [comment]
Does this also mean that I can reference SAPI's folders from TRT? Plus, Is the download from the public Trade interface already caching everything in SAPI?

**Comment by agnessa** [comment]
Please note the two apps may be (possibly will be) hosted on separate machines, so you cannot directly reference the file system. It is possible to share a file system between machines, but I wonder if we might consider "softer" ways of doing it, e.g. once submission processed trt calls an endpoint in SAPI to instruct it to flush cache. Only the trade downloads need flushing. Another way to do it could possibly be to utilise the NOTIFY / LISTEN mechanism in postgres (as in listerer in sapi, notifier in the copy_sandbox_shipments procedure) - not sure which is easier.

**Pull request merged**
